/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ship.glb -t 
*/

import { useGLTF } from '@react-three/drei';
import type { ThreeElements } from '@react-three/fiber';
import { useFrame } from '@react-three/fiber';
import * as React from 'react';
import * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import { useShipPhysics } from '../hooks/useShipPhysics';

type GLTFResult = GLTF & {
  nodes: {
    ['12219_boat_v2_L2_1']: THREE.Mesh;
    ['12219_boat_v2_L2_2']: THREE.Mesh;
    ['12219_boat_v2_L2_3']: THREE.Mesh;
    ['12219_boat_v2_L2_4']: THREE.Mesh;
    ['12219_boat_v2_L2_5']: THREE.Mesh;
    ['12219_boat_v2_L2_6']: THREE.Mesh;
    ['12219_boat_v2_L2_7']: THREE.Mesh;
    ['12219_boat_v2_L2_8']: THREE.Mesh;
  };
  materials: {
    white: THREE.MeshPhysicalMaterial;
    boat_elements_black: THREE.MeshPhysicalMaterial;
    boat_glass: THREE.MeshPhysicalMaterial;
    boat_screw_hooks_bronze: THREE.MeshPhysicalMaterial;
    boat_silver: THREE.MeshPhysicalMaterial;
    boat_buffer: THREE.MeshPhysicalMaterial;
    boat_roof_accessory: THREE.MeshPhysicalMaterial;
    boat_body: THREE.MeshPhysicalMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Ship(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/ship.glb') as unknown as GLTFResult;

  const shipRef = React.useRef<THREE.Group>(null);

  useShipPhysics(shipRef, -1);

  React.useEffect(() => {
    Object.values(materials).forEach((mat) => {
      if (mat) {
        mat.transparent = true;
        mat.alphaTest = 0.01;
      }
    });
  }, [materials]);

  useFrame((state) => {
    if (shipRef.current) {
      const cam = state.camera.position;
      const shipPos = shipRef.current.position;

      const dist = cam.distanceTo(shipPos);

      const horizonFade = THREE.MathUtils.clamp((dist - 900.0) / 600.0, 0.0, 1.0);

      const altitudeFade = THREE.MathUtils.clamp((cam.y - 190.0) / 100.0, 0.0, 1.0);

      const totalFade = Math.max(horizonFade, altitudeFade);
      const currentOpacity = 1.0 - totalFade;

      Object.values(materials).forEach((mat) => {
        if (mat) {
          mat.opacity = currentOpacity;
        }
      });
    }
  });

  return (
    <group ref={shipRef} {...props} dispose={null}>
      <group rotation={[0, 90, 0]} position={[0, 0, -4]} scale={0.005}>
        <mesh geometry={nodes['12219_boat_v2_L2_1'].geometry} material={materials.white} />
        <mesh
          geometry={nodes['12219_boat_v2_L2_2'].geometry}
          material={materials.boat_elements_black}
        />
        <mesh geometry={nodes['12219_boat_v2_L2_3'].geometry} material={materials.boat_glass} />
        <mesh
          geometry={nodes['12219_boat_v2_L2_4'].geometry}
          material={materials.boat_screw_hooks_bronze}
        />
        <mesh geometry={nodes['12219_boat_v2_L2_5'].geometry} material={materials.boat_silver} />
        <mesh geometry={nodes['12219_boat_v2_L2_6'].geometry} material={materials.boat_buffer} />
        <mesh
          geometry={nodes['12219_boat_v2_L2_7'].geometry}
          material={materials.boat_roof_accessory}
        />
        <mesh geometry={nodes['12219_boat_v2_L2_8'].geometry} material={materials.boat_body} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/ship.glb');
