/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar.glb -t 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useGraph } from '@react-three/fiber';
import React, { useEffect } from 'react';
import * as THREE from 'three';
import { type GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'Idle' | 'JumpAttack' | 'Typing' | 'Walking' | 'Waving';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    ['Body_(merged)002']: THREE.SkinnedMesh;
    ['Body_(merged)002_1']: THREE.SkinnedMesh;
    ['Body_(merged)002_2']: THREE.SkinnedMesh;
    ['Body_(merged)002_3']: THREE.SkinnedMesh;
    ['Body_(merged)002_4']: THREE.SkinnedMesh;
    Hair: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_1']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_2']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_3']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_4']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_5']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_6']: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ['N00_000_00_Body_00_SKIN (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_004_01_Shoes_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_001_01_Bottoms_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_005_01_Tops_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_HairBack_00_HAIR (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_Hair_00_HAIR (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceMouth_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeIris_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeHighlight_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_Face_00_SKIN (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeWhite_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceBrow_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceEyeline_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Avatar(props: any) {
  const group = React.useRef<THREE.Group>(null);

  const { scene, animations } = useGLTF('/models/avatar.glb');

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.alphaTest = 0.5;
      material.transparent = false;
      material.depthWrite = true;
      material.needsUpdate = true;
    });
  }, [actions, materials]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.018}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Body">
            <skinnedMesh
              name="Body_(merged)002"
              geometry={nodes['Body_(merged)002'].geometry}
              material={materials['N00_000_00_Body_00_SKIN (Instance).002']}
              skeleton={nodes['Body_(merged)002'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_1"
              geometry={nodes['Body_(merged)002_1'].geometry}
              material={materials['N00_004_01_Shoes_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_1'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_2"
              geometry={nodes['Body_(merged)002_2'].geometry}
              material={materials['N00_001_01_Bottoms_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_2'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_3"
              geometry={nodes['Body_(merged)002_3'].geometry}
              material={materials['N00_005_01_Tops_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_3'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_4"
              geometry={nodes['Body_(merged)002_4'].geometry}
              material={materials['N00_000_00_HairBack_00_HAIR (Instance).002']}
              skeleton={nodes['Body_(merged)002_4'].skeleton}
            />
          </group>
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials['N00_000_Hair_00_HAIR (Instance).002']}
            skeleton={nodes.Hair.skeleton}
          />
          <group name="Face">
            <skinnedMesh
              name="Face_(merged)(Clone)002"
              geometry={nodes['Face_(merged)(Clone)002'].geometry}
              material={materials['N00_000_00_FaceMouth_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_1"
              geometry={nodes['Face_(merged)(Clone)002_1'].geometry}
              material={materials['N00_000_00_EyeIris_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_1'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_1'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_1'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_2"
              geometry={nodes['Face_(merged)(Clone)002_2'].geometry}
              material={materials['N00_000_00_EyeHighlight_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_2'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_2'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_2'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_3"
              geometry={nodes['Face_(merged)(Clone)002_3'].geometry}
              material={materials['N00_000_00_Face_00_SKIN (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_3'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_3'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_3'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_4"
              geometry={nodes['Face_(merged)(Clone)002_4'].geometry}
              material={materials['N00_000_00_EyeWhite_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_4'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_4'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_4'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_5"
              geometry={nodes['Face_(merged)(Clone)002_5'].geometry}
              material={materials['N00_000_00_FaceBrow_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_5'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_5'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_5'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_6"
              geometry={nodes['Face_(merged)(Clone)002_6'].geometry}
              material={materials['N00_000_00_FaceEyeline_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_6'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_6'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_6'].morphTargetInfluences}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/avatar.glb');
