/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar.glb -t 
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useFrame, useGraph } from '@react-three/fiber';
import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { type GLTF, SkeletonUtils } from 'three-stdlib';

type ActionName = 'Idle' | 'JumpAttack' | 'Typing' | 'Walking' | 'Waving';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

interface AvatarProps {
  animation: ActionName;
  walkSpeedRef: React.RefObject<number>;
}

type GLTFResult = GLTF & {
  nodes: {
    ['Body_(merged)002']: THREE.SkinnedMesh;
    ['Body_(merged)002_1']: THREE.SkinnedMesh;
    ['Body_(merged)002_2']: THREE.SkinnedMesh;
    ['Body_(merged)002_3']: THREE.SkinnedMesh;
    ['Body_(merged)002_4']: THREE.SkinnedMesh;
    Hair: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_1']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_2']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_3']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_4']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_5']: THREE.SkinnedMesh;
    ['Face_(merged)(Clone)002_6']: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ['N00_000_00_Body_00_SKIN (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_004_01_Shoes_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_001_01_Bottoms_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_005_01_Tops_01_CLOTH (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_HairBack_00_HAIR (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_Hair_00_HAIR (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceMouth_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeIris_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeHighlight_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_Face_00_SKIN (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_EyeWhite_00_EYE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceBrow_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
    ['N00_000_00_FaceEyeline_00_FACE (Instance).002']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Avatar({ animation, walkSpeedRef, ...props }: AvatarProps) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF('/models/avatar.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  const initialHeadRot = useRef<THREE.Euler | null>(null);
  const globalMouse = useRef(new THREE.Vector2(0, 0));

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      globalMouse.current.x = (event.clientX / window.innerWidth) * 2 - 1;
      globalMouse.current.y = -(event.clientY / window.innerHeight) * 2 + 1;
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  useEffect(() => {
    animations.forEach((clip) => {
      if (clip.name === 'Idle' || clip.name === 'Waving') {
        clip.tracks = clip.tracks.filter(
          (track) => !track.name.includes('Head') && !track.name.includes('Neck')
        );
      }
    });
  }, [animations]);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.alphaTest = 0.5;
      material.transparent = false;
      material.depthWrite = true;
      material.needsUpdate = true;
    });
  }, [actions, materials]);

  useEffect(() => {
    const currentAction = actions[animation];

    if (currentAction) {
      currentAction.reset().fadeIn(0.5).play();

      return () => {
        currentAction.fadeOut(0.5);
      };
    }
  }, [animation, actions]);

  useFrame((_, delta) => {
    const walkingAction = actions['Walking'];
    if (animation === 'Walking' && walkingAction && walkSpeedRef) {
      walkingAction.setEffectiveTimeScale(walkSpeedRef.current);
    }

    if (!group.current) return;
    const head =
      group.current.getObjectByName('mixamorigHead') ||
      group.current.getObjectByName('mixamorigNeck');

    if (head) {
      if (!initialHeadRot.current) {
        initialHeadRot.current = head.rotation.clone();
      }

      if (animation === 'Idle' || animation === 'Waving') {
        let targetPitch = initialHeadRot.current.x + -globalMouse.current.y * 0.4;
        let targetYaw = initialHeadRot.current.y + globalMouse.current.x * 0.6;

        const maxPitch = 0.5;
        const maxYaw = 0.6;

        targetPitch = THREE.MathUtils.clamp(
          targetPitch,
          initialHeadRot.current.x - maxPitch,
          initialHeadRot.current.x + maxPitch
        );

        targetYaw = THREE.MathUtils.clamp(
          targetYaw,
          initialHeadRot.current.y - maxYaw,
          initialHeadRot.current.y + maxYaw
        );

        head.rotation.x = THREE.MathUtils.lerp(head.rotation.x, targetPitch, delta * 6);
        head.rotation.y = THREE.MathUtils.lerp(head.rotation.y, targetYaw, delta * 6);

        head.matrixAutoUpdate = true;
        head.updateMatrix();
      } else {
        head.rotation.x = THREE.MathUtils.lerp(
          head.rotation.x,
          initialHeadRot.current.x,
          delta * 6
        );
        head.rotation.y = THREE.MathUtils.lerp(
          head.rotation.y,
          initialHeadRot.current.y,
          delta * 6
        );
      }
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.018}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Body">
            <skinnedMesh
              name="Body_(merged)002"
              geometry={nodes['Body_(merged)002'].geometry}
              material={materials['N00_000_00_Body_00_SKIN (Instance).002']}
              skeleton={nodes['Body_(merged)002'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_1"
              geometry={nodes['Body_(merged)002_1'].geometry}
              material={materials['N00_004_01_Shoes_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_1'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_2"
              geometry={nodes['Body_(merged)002_2'].geometry}
              material={materials['N00_001_01_Bottoms_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_2'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_3"
              geometry={nodes['Body_(merged)002_3'].geometry}
              material={materials['N00_005_01_Tops_01_CLOTH (Instance).002']}
              skeleton={nodes['Body_(merged)002_3'].skeleton}
            />
            <skinnedMesh
              name="Body_(merged)002_4"
              geometry={nodes['Body_(merged)002_4'].geometry}
              material={materials['N00_000_00_HairBack_00_HAIR (Instance).002']}
              skeleton={nodes['Body_(merged)002_4'].skeleton}
            />
          </group>
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials['N00_000_Hair_00_HAIR (Instance).002']}
            skeleton={nodes.Hair.skeleton}
          />
          <group name="Face">
            <skinnedMesh
              name="Face_(merged)(Clone)002"
              geometry={nodes['Face_(merged)(Clone)002'].geometry}
              material={materials['N00_000_00_FaceMouth_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_1"
              geometry={nodes['Face_(merged)(Clone)002_1'].geometry}
              material={materials['N00_000_00_EyeIris_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_1'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_1'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_1'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_2"
              geometry={nodes['Face_(merged)(Clone)002_2'].geometry}
              material={materials['N00_000_00_EyeHighlight_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_2'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_2'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_2'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_3"
              geometry={nodes['Face_(merged)(Clone)002_3'].geometry}
              material={materials['N00_000_00_Face_00_SKIN (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_3'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_3'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_3'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_4"
              geometry={nodes['Face_(merged)(Clone)002_4'].geometry}
              material={materials['N00_000_00_EyeWhite_00_EYE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_4'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_4'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_4'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_5"
              geometry={nodes['Face_(merged)(Clone)002_5'].geometry}
              material={materials['N00_000_00_FaceBrow_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_5'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_5'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_5'].morphTargetInfluences}
            />
            <skinnedMesh
              name="Face_(merged)(Clone)002_6"
              geometry={nodes['Face_(merged)(Clone)002_6'].geometry}
              material={materials['N00_000_00_FaceEyeline_00_FACE (Instance).002']}
              skeleton={nodes['Face_(merged)(Clone)002_6'].skeleton}
              morphTargetDictionary={nodes['Face_(merged)(Clone)002_6'].morphTargetDictionary}
              morphTargetInfluences={nodes['Face_(merged)(Clone)002_6'].morphTargetInfluences}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/avatar.glb');
